package cn.msds.model
import cn.msds.constant.ConstantRuleResult;
import  cn.msds.util.CheatActionImpl;
query "end Cheat"
	//cheat:Cheat()
	apply:Apply()
end

rule "cheat1"
    //ruleflow-group "CheatRule"
    no-loop true
	when
		//申请表手机号与电商账户存的手机号不一致
   		$apply: Apply($apply.getPhoneNum()!=$apply.getBnRecivePhone());
	then
   		$apply.setCheatType(ConstantRuleResult.Rule_cheat_phnosame);
   		update($apply);
   		//System.out.println("申请表手机号与电商账户存的手机号不一致");
   		System.out.println("cheat1"+"   "+ConstantRuleResult.Rule_cheat_phnosame);
end
rule "cheat2"
    //ruleflow-group "CheatRule"
    no-loop true
	when
		//单一cust_nbr关联手机号码大于等于3个
   		$apply: Apply();
   		$action32:CheatActionImpl($action32.getPhones($apply.getUuid())>=3)
	then
   		$apply.setCheatType(ConstantRuleResult.Rule_cheat_mcontact);
   		update($apply);
   		//System.out.println("单一cust_nbr关联手机号码大于等于3个");
   		System.out.println("cheat2"+"      "+ConstantRuleResult.Rule_cheat_mcontact);
end

rule "cheat3"
    //ruleflow-group "CheatRule"
    no-loop true
	when
		//同一手机号关联姓名大于等于6个
   		$apply: Apply();
   		$action32:CheatActionImpl($action32.getCusts($apply.getPhoneNum())>=6)
	then
   		$apply.setCheatType(ConstantRuleResult.Rule_cheat_muuid);
   		update($apply);
   		//System.out.println("同一手机号关联姓名大于等于6个");
   		System.out.println("cheat3"+"     "+ConstantRuleResult.Rule_cheat_muuid);
end

rule "cheat4"
    //ruleflow-group "CheatRule"
    no-loop true
	when
		//如申请人IP 24小时内申请次数大于等于3次 
   		$apply: Apply();
   		$action33:CheatActionImpl($action33.getIps($apply.getUuid())>=3)
	then
   		$apply.setCheatType(ConstantRuleResult.Rule_cheat_mregister);
   		update($apply);
   		//System.out.println("如申请人IP 24小时内申请次数大于等于3次 ");
   		System.out.println("cheat4"+"     "+ConstantRuleResult.Rule_cheat_mregister);
end
