package cn.msds.model
import  com.hxrainbow.rule.model.TempCreditCheck;
query "end TempCreditCheck"
	tempCreditCheck:TempCreditCheck()
end

rule "industry1"
    ruleflow-group "industry"
    no-loop true
	when
		//“公司类型”=2
   		$apply: Apply($apply.getIndustry()==2);
   		$tempCreditCheck:TempCreditCheck();
	then
   		$tempCreditCheck.setPreIncome($tempCreditCheck.getIncome()*1.2);
   		System.out.println("industry1"+"   "+$tempCreditCheck.getPreIncome());
   		update($tempCreditCheck);
end
rule "industry2"
    ruleflow-group "industry"
    no-loop true
	when
		//“公司类型”=1
   		$apply: Apply($apply.getIndustry()==1);
   		$tempCreditCheck:TempCreditCheck();
	then
   		$tempCreditCheck.setPreIncome($tempCreditCheck.getIncome()*1.0);
   		System.out.println("industry2"+"   "+$tempCreditCheck.getPreIncome());
   		update($tempCreditCheck);
end

rule "industry3"
    ruleflow-group "industry"
    no-loop true
	when
		//
   		$apply: Apply($apply.getIndustry()!=2&&$apply.getIndustry()!=1);
   		$tempCreditCheck:TempCreditCheck();
	then
   		$tempCreditCheck.setPreIncome($tempCreditCheck.getIncome()*0.8);
   		System.out.println("industry3"+"   "+$tempCreditCheck.getPreIncome());
   		update($tempCreditCheck);
end
