package cn.msds.model
import  cn.msds.model.temp.TempCreditCheck;
import  cn.msds.util.CreditCheckActionImpl;
query "end TempCreditCheck"
	tempCreditCheck:TempCreditCheck()
end

rule "point1"
    ruleflow-group "point"
    no-loop true
	when
		//“申请评分”<560
   		$apply: Apply();
   		$tempCreditCheck:TempCreditCheck();
   		$creditCheckActionImpl:CreditCheckActionImpl($creditCheckActionImpl.getApplyPoint($apply)<560);
	then
   		$tempCreditCheck.setApplyPointType(3);
   		$apply.setScore($creditCheckActionImpl.getApplyPoint($apply));
   		$apply.setGrade(3);
   		System.out.println("point1"+"   "+$tempCreditCheck.getApplyPointType());
   		update($tempCreditCheck);
   		update($apply);
end
rule "point2"
    ruleflow-group "point"
    no-loop true
	when
		//560<=“申请评分”<630
   		$apply: Apply();
   		$tempCreditCheck:TempCreditCheck();
   		$creditCheckActionImpl:CreditCheckActionImpl($creditCheckActionImpl.getApplyPoint($apply)>=560&&$creditCheckActionImpl.getApplyPoint($apply)<630);
	then
   		$tempCreditCheck.setApplyPointType(2);
   		$apply.setScore($creditCheckActionImpl.getApplyPoint($apply));
   		$apply.setGrade(2);
   		System.out.println("point2"+"   "+$tempCreditCheck.getApplyPointType());
   		update($tempCreditCheck);
   		update($apply);
end

rule "point3"
    ruleflow-group "point"
    no-loop true
	when
		//
   		$apply: Apply();
   		$tempCreditCheck:TempCreditCheck();
   		$creditCheckActionImpl:CreditCheckActionImpl($creditCheckActionImpl.getApplyPoint($apply)>=630);
	then
   		$tempCreditCheck.setApplyPointType(1);
   		$apply.setScore($creditCheckActionImpl.getApplyPoint($apply));
   		$apply.setGrade(1);
   		System.out.println("point3"+"   "+$tempCreditCheck.getApplyPointType());
   		update($tempCreditCheck);
   		update($apply);
end
